
---
collections:
  - name: community.docker
    version: ">=3.10.0,<4.0.0"
  - name: community.general
    version: ">=9.0.0"
  - name: telekom_mms.icinga_director
    # dacă vrei să fixezi o versiune, poți:
    # version: ">=1.0.0"
