stages:
  - check
  - copy
  - deploy
  - monitoring

variables:
  ANSIBLE_PLAYBOOK_CHECK: "ansible-mongo/playbook/check.yaml"
  ANSIBLE_PLAYBOOK_COPY: "ansible-mongo/playbook/mongo_copy.yaml"
  ANSIBLE_PLAYBOOK_DEPLOY: "ansible-mongo/playbook/mongo_deploy.yaml"
  ANSIBLE_FORCE_COLOR: "true"
  ANSIBLE_HOST_KEY_CHECKING: "False"

check:
  stage: check
  tags:
    - shell-office-shared-runner
  script:
    - >
     ansible-playbook  "$ANSIBLE_PLAYBOOK_CHECK"
     --inventory-file ansible-mongo/inventory.yml
  only:
    - main


mongo_copy:
  stage: copy
  tags:
    - shell-office-shared-runner
  before_script:
    - ansible-galaxy collection install -r ansible-mongo/requirements.yml
  script:
    - >
     ansible-playbook  "$ANSIBLE_PLAYBOOK_COPY"
     --inventory-file ansible-mongo/inventory.yml
  only:   
    - main
  when: manual


mongo_deploy:
  stage: deploy
  tags:
    - shell-office-shared-runner
  before_script:
    - ansible-galaxy collection install -r ansible-mongo/requirements.yml
  script:
    - >
     ansible-playbook  "$ANSIBLE_PLAYBOOK_DEPLOY"
     --inventory-file ansible-mongo/inventory.yml
  only:
    - main
  when: manual


