---
- import_tasks: tasks/ping_check.yml
- import_tasks: tasks/port_check.yml
#- import_tasks: tasks/resource_check.yml
#- import_tasks: tasks/recommend_hosts.yml
#- import_tasks: tasks/docker_ram.yml
#- import_tasks: tasks/final_report.yml
#- import_tasks: tasks/generate_report_html.yml
