all:
  children:
    mongo_nodes:
      hosts:
        mongo1:
          ansible_host: 10.192.24.90
        mongo2:
          ansible_host: 10.192.24.91
        mongo3:
          ansible_host: 10.192.24.92

    mongo:
      children:
        mongo_nodes:

    check:
      children:
        mongo_nodes:
